// cliente-react/src/components/ModalForm.jsx
import React from 'react';

export default function ModalForm({
  show,
  title,
  icon,
  fields = [],
  onChange,
  onSubmit,
  onClose,
  error,
  submitLabel = 'Guardar',
}) {
  const [localError, setLocalError] = React.useState({});

  function validateEmail(email) {
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
  }
  function validateDocument(doc) {
    return /^\d{10}$/.test(doc);
  }

  function validatePhone(phone) {
    return /^\d{10,}$/.test(phone);
  }

  function handleSubmit(e) {
    e.preventDefault();
    let errors = {};
    let values = {};
    fields.forEach(f => { values[f.name] = f.value; });
    if ('document' in values && !validateDocument(values.document)) {
      errors.document = 'La cédula debe ser numérica y tener exactamente 10 dígitos.';
    }
    if ('email' in values && !validateEmail(values.email)) {
      errors.email = 'El correo no es válido.';
    }
    if ('phone' in values && !validatePhone(values.phone)) {
      errors.phone = 'El teléfono debe tener al menos 10 dígitos.';
    }
    setLocalError(errors);
    if (Object.keys(errors).length > 0) return;
    if (onSubmit) onSubmit(e);
  }

  if (!show) return null;
  return (
    <div style={{
      position: 'fixed',
      top: 0, left: 0, width: '100vw', height: '100vh',
      zIndex: 2000,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    }}>
      {/* Fondo opaco */}
      <div style={{
        position: 'absolute',
        top: 0, left: 0, width: '100vw', height: '100vh',
        background: 'rgba(0,0,0,0.35)',
        zIndex: 1
      }} onClick={onClose}></div>
      {/* Card modal */}
      <div className="card shadow-lg p-0" style={{minWidth: 370, maxWidth: 420, width: '100%', borderRadius: '1.3rem', zIndex: 2, position: 'relative'}}>
        {/* Botón X arriba a la derecha */}
        <button type="button" className="btn btn-light btn-sm d-flex align-items-center justify-content-center" style={{position:'absolute', top:14, right:14, width:32, height:32, borderRadius:'50%', fontSize:20, border:'none', boxShadow:'0 1px 4px #0001', zIndex:10}} onClick={onClose} aria-label="Cerrar">
          <span aria-hidden="true">&times;</span>
        </button>
        <div className="card-header bg-white border-0 pb-0 d-flex align-items-center" style={{borderRadius:'1.3rem 1.3rem 0 0'}}>
          <h5 className="fw-bold mb-0">
            {icon}{title}
          </h5>
        </div>
  <form onSubmit={handleSubmit} autoComplete="off">
          <div className="card-body pt-3 pb-2 px-4">
            {fields.map(field => (
              <div className="mb-3" key={field.name}>
                <label className="form-label">
                  {field.label}
                  {field.required && <span className="text-danger ms-1">*</span>}
                </label>
                {field.type === 'select' ? (
                  <select
                    name={field.name}
                    className="form-control"
                    value={field.value}
                    onChange={e => onChange(field.name, e.target.value)}
                    required={field.required}
                  >
                    <option value="">Seleccione...</option>
                    {field.options && field.options.map(opt => (
                      <option key={opt.value} value={opt.value}>{opt.label}</option>
                    ))}
                  </select>
                ) : (
                  <input
                    name={field.name}
                    type={field.type}
                    className="form-control"
                    value={field.value}
                    onChange={e => onChange(field.name, e.target.value)}
                    required={field.required}
                    autoFocus={field.autoFocus}
                  />
                )}
                {localError && localError[field.name] && (
                  <div style={{ color: '#dc2626', fontSize: '.92em', marginTop: 2 }}>{localError[field.name]}</div>
                )}
              </div>
            ))}
            {error && (
              <div style={{ color: '#dc2626', fontSize: '.97em', marginTop: 8, marginBottom: 0, textAlign: 'right' }}>{error}</div>
            )}
          </div>
          <div style={{height: '1.5rem'}}></div>
          <div className="card-footer bg-white border-0 pb-3 px-4 d-flex justify-content-end" style={{borderRadius:'0 0 1.3rem 1.3rem'}}>
            <div className="d-flex gap-4">
              <button type="button" className="btn btn-outline-secondary" onClick={onClose}>Cancelar</button>
              <button type="submit" className="btn btn-primary">{submitLabel}</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
}

// ClientAngular/src/app/components/modal-form.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-modal-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  styleUrls: ['./modal-form.component.css'],
  template: `
    <div *ngIf="show">
      <div class="modalform-backdrop" (click)="onClose.emit()"></div>
      <div class="modalform-outer">
        <div class="modalform-card">
          <button type="button" class="modalform-x" (click)="onClose.emit()" aria-label="Cerrar">
            <span aria-hidden="true">&times;</span>
          </button>
          <div class="modalform-header">
            <span *ngIf="icon" class="me-2">{{ icon }}</span>
            <span class="modalform-title">{{ title }}</span>
          </div>
          <form (ngSubmit)="handleSubmit($event)" autocomplete="off">
            <div class="card-body pt-3 pb-2 px-4">
              <div class="mb-3" *ngFor="let field of fields">
                <label class="form-label">
                  {{ field.label }}
                  <span *ngIf="field.required" class="text-danger ms-1">*</span>
                </label>
                <ng-container [ngSwitch]="field.type">
                  <select *ngSwitchCase="'select'" [name]="field.name" class="form-control" [(ngModel)]="field.value" (ngModelChange)="onChange.emit({ name: field.name, value: $event })" [required]="field.required">
                    <option value="">Seleccione...</option>
                    <option *ngFor="let opt of field.options" [value]="opt.value">{{ opt.label }}</option>
                  </select>
                  <input *ngSwitchDefault [name]="field.name" [type]="field.type" class="form-control" [(ngModel)]="field.value" (ngModelChange)="onChange.emit({ name: field.name, value: $event })" [required]="field.required" [autofocus]="field.autoFocus" />
                </ng-container>
                <div *ngIf="localError[field.name]" style="color: #dc2626; font-size: .92em; margin-top: 2px;">{{ localError[field.name] }}</div>
              </div>
              <div *ngIf="error" class="modalform-error">{{ error }}</div>
            </div>
            <div style="height: 1.5rem"></div>
            <div class="modalform-footer">
              <button type="button" class="btn btn-outline-secondary me-3" (click)="onClose.emit()">Cancelar</button>
              <button type="submit" class="btn btn-primary">{{ submitLabel || 'Guardar' }}</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  `
})
export class ModalFormComponent {
  @Input() show = false;
  @Input() title = '';
  @Input() icon?: string;
  @Input() fields: any[] = [];
  @Input() error: string = '';
  @Input() submitLabel = 'Guardar';
  @Input() form: any;
  @Output() onChange = new EventEmitter<any>();
  @Output() onSubmit = new EventEmitter<any>();
  @Output() onClose = new EventEmitter<void>();

  localError: any = {};

  validateEmail(email: string) {
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
  }
  validateDocument(doc: string) {
    return /^\d{10}$/.test(doc);
  }
  validatePhone(phone: string) {
    return /^\d{10,}$/.test(phone);
  }

  handleSubmit(e: Event) {
    e.preventDefault();
    const errors: any = {};
    const values: any = {};
    this.fields.forEach(f => { values[f.name] = f.value; });
    // Validar campos requeridos vacíos
    this.fields.forEach(f => {
      const val = values[f.name];
      // Validación por tipo
      if (f.type === 'number' && val && (!/^\d+$/.test(val.toString()) || parseInt(val, 10) <= 0)) {
        errors[f.name] = 'Debe ser un número entero positivo.';
      } else if (f.type === 'email' && val && !this.validateEmail(val)) {
        errors[f.name] = 'El correo no es válido.';
      } else if ((f.type === 'tel' || f.type === 'phone') && val && !this.validatePhone(val)) {
        errors[f.name] = 'El teléfono debe tener al menos 10 dígitos.';
      } else if (f.name === 'document' && val && !this.validateDocument(val)) {
        errors.document = 'La cédula debe ser numérica y tener exactamente 10 dígitos.';
      } else if (f.required && (!val || val.toString().trim() === '')) {
        errors[f.name] = 'Este campo es obligatorio.';
      }
    });
    this.localError = errors;
    if (Object.keys(errors).length > 0) return;
    this.onSubmit.emit(e);
  }
}
