// cliente-react/src/components/TableCrud.jsx
import React, { useState } from 'react';
import './TableCrud.css';
import { PiPencilBold, PiTrashBold, PiUsersBold, PiEyeBold } from 'react-icons/pi';

/**
 * TableCrud
 * Props:
 * - columns: array de { key, label }
 * - data: array de objetos (los registros)
 * - onEdit: function (row) (opcional)
 * - onDelete: function (row) (opcional)
 * - loading: boolean (opcional)
 * - emptyText: string (opcional)
 *
 * Ejemplo de uso:
 * <TableCrud
 *   columns={[
 *     { key: 'number', label: 'Número' },
 *     { key: 'type', label: 'Tipo' },
 *     { key: 'capacity', label: 'Capacidad' },
 *     { key: 'status', label: 'Estado' },
 *   ]}
 *   data={rooms}
 *   onEdit={room => ...}
 *   onDelete={room => ...}
 *   loading={loading}
 *   emptyText="No hay habitaciones registradas."
 * />
 */
export default function TableCrud({ columns, data, onEdit, onDelete, onView, onValidate, loading, emptyText }) {
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [rowToDelete, setRowToDelete] = useState(null);
  const [deleteError, setDeleteError] = useState(null);
  // Render especial para habitaciones
  function renderCell(col, row) {
    if (col.key === 'status') {
      const status = row.status;
      let badgeClass = 'bg-secondary';
      // Habitaciones
      if (status === 'disponible') badgeClass = 'bg-success';
      else if (status === 'ocupada') badgeClass = 'bg-danger';
      else if (status === 'mantenimiento') badgeClass = 'bg-warning text-dark';
      // Reservas
      else if (status === 'pendiente') badgeClass = 'bg-warning text-dark';
      else if (status === 'confirmada') badgeClass = 'bg-success';
      else if (status === 'cancelada') badgeClass = 'bg-danger';
      else if (status === 'finalizada') badgeClass = 'bg-primary';
      return <span className={`badge ${badgeClass}`}>{status ? status.charAt(0).toUpperCase() + status.slice(1) : ''}</span>;
    }
    if (col.key === 'capacity') {
      return <span><PiUsersBold style={{marginRight: 6, fontSize: '1.1em', verticalAlign: 'middle'}} /> {row.capacity}</span>;
    }
    return row[col.key];
  }
  // Validación para edición/creación
  function handleEdit(row) {
    if (onValidate) {
      const error = onValidate(row);
      if (error) {
        alert(error);
        return;
      }
    }
    if (onEdit) onEdit(row);
  }

  // Validación para creación (si se usa onValidate en onEdit)
  function handleCreate(row) {
    if (onValidate) {
      const error = onValidate(row);
      if (error) {
        alert(error);
        return false;
      }
    }
    return true;
  }

  return (
    <div className="table-responsive">
      <table className="table table-crud align-middle table-hover border">
        <thead className="table-light">
          <tr>
            {columns.map(col => (
              <th key={col.key}>{col.label}</th>
            ))}
            {(onView || onEdit || onDelete) && <th>Acciones</th>}
          </tr>
        </thead>
        <tbody>
          {loading ? (
            <tr><td colSpan={columns.length + 1} className="text-center">Cargando...</td></tr>
          ) : data.length === 0 ? (
            <tr><td colSpan={columns.length + 1} className="text-center text-muted">{emptyText || 'Sin registros.'}</td></tr>
          ) : (
            data.map(row => (
              <tr key={row.id || JSON.stringify(row)} className="table-row-crud">
                {columns.map(col => (
                  <td key={col.key}>{col.render ? col.render(row) : renderCell(col, row)}</td>
                ))}
                {(onView || onEdit || onDelete) && (
                  <td>
                    <div className="d-flex gap-2" style={{gap: '10px'}}>
                      {onView && <button className="btn btn-sm btn-primary" onClick={() => onView(row)} title="Ver"><PiEyeBold /></button>}
                      {onEdit && <button className="btn btn-sm btn-warning" onClick={() => handleEdit(row)} title="Editar"><PiPencilBold /></button>}
                      {onDelete && <button className="btn btn-sm btn-danger" onClick={() => { setRowToDelete(row); setShowDeleteModal(true); }} title="Eliminar"><PiTrashBold /></button>}
                    </div>
                  </td>
                )}
              </tr>
            ))
          )}
        </tbody>
      </table>
      <style>{`
        .table-row-crud:hover { background: #f1f5f9; }
        .badge.bg-success { background: #22c55e !important; }
        .badge.bg-danger { background: #ef4444 !important; }
        .badge.bg-warning { background: #fbbf24 !important; }
  .badge.bg-primary { background: #3b82f6 !important; }
  .badge.bg-warning.text-dark { color: #b45309 !important; background: #fbbf24 !important; }
  .badge.bg-danger { background: #ef4444 !important; }
  .badge.bg-success { background: #22c55e !important; }
  .modal-backdrop-crud {
          position: fixed;
          top: 0; left: 0; right: 0; bottom: 0;
          background: rgba(30,41,59,0.32);
          z-index: 1000;
          display: flex;
          align-items: center;
          justify-content: center;
        }
        .modal-crud {
          background: var(--color-surface, #f8fafc);
          color: #fff;
          border-radius: 1rem;
          box-shadow: 0 8px 32px rgba(0,0,0,0.18);
          padding: 2.2rem 2.2rem 1.5rem 2.2rem;
          min-width: 320px;
          max-width: 95vw;
          text-align: center;
        }
        .modal-crud h5, .modal-crud .btn, .modal-crud div, .modal-crud p, .modal-crud span {
          color: #fff !important;
        }
        .modal-crud h5 { font-size: 1.1rem; font-weight: 700; margin-bottom: 1.2rem; color: #1e293b; }
        .modal-crud .btn { margin: 0 0.5rem; min-width: 90px; }
      `}</style>

      {showDeleteModal && (
        <div className="modal-backdrop-crud">
          <div className="modal-crud">
            <h5>¿Seguro que deseas eliminar este registro?</h5>
            <div style={{marginBottom: '1.2rem', color: '#64748b', fontSize: '.98rem'}}>
              Esta acción no se puede deshacer.
            </div>
            <div>
              <button className="btn btn-danger" onClick={async () => {
                setDeleteError(null);
                if (onDelete && rowToDelete) {
                  try {
                    await onDelete(rowToDelete);
                    setShowDeleteModal(false);
                    setRowToDelete(null);
                  } catch (err) {
                    setDeleteError(err?.message || (err?.error) || 'Error al eliminar');
                  }
                }
              }}>Eliminar</button>
              <button className="btn btn-secondary" onClick={() => {
                setShowDeleteModal(false);
                setRowToDelete(null);
                setDeleteError(null);
              }}>Cancelar</button>
            </div>
            {deleteError && <div style={{ color: '#ef4444', marginTop: 10, fontWeight: 500 }}>{deleteError}</div>}
          </div>
        </div>
      )}
    </div>
  );
}

// ClientAngular/src/app/components/table-crud.component.ts
import { Component, Input, Output, EventEmitter, OnChanges, ChangeDetectorRef } from '@angular/core';
import { CommonModule, TitleCasePipe } from '@angular/common';


@Component({
  selector: 'app-table-crud',
  standalone: true,
  imports: [CommonModule, TitleCasePipe],
  styleUrls: ['./table-crud.component.css'],
  template: `
    <div class="table-crud-wrapper">
      <div style="padding-top: 1.5rem;"></div>
      <div class="table-responsive">
        <table class="table table-crud table-bordered table-hover align-middle">
          <thead>
            <tr>
              <th *ngFor="let col of columns">{{ col.label }}</th>
              <th *ngIf="onEdit || onDelete">Acciones</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngIf="loading">
              <td [attr.colspan]="columns.length + 1" class="text-center">Cargando...</td>
            </tr>
            <tr *ngIf="!loading && (!data || data.length === 0)">
              <td [attr.colspan]="columns.length + 1" class="text-center text-muted">{{ emptyText || 'Sin registros.' }}</td>
            </tr>
            <tr *ngFor="let row of data">
              <td *ngFor="let col of columns">
                <ng-container *ngIf="col.key === 'status'; else normalCell">
                  <span class="badge" [ngClass]="'estado-' + (row[col.key] || '').toLowerCase()">{{ row[col.key] | titlecase }}</span>
                </ng-container>
                <ng-template #normalCell>
                  <ng-container *ngIf="col.key === 'capacity'; else defaultCell">
                    <i class="bi bi-people me-1"></i> {{ row[col.key] }}
                  </ng-container>
                  <ng-template #defaultCell>{{ row[col.key] }}</ng-template>
                </ng-template>
              </td>
              <td *ngIf="onEdit || onDelete">
                <button *ngIf="onEdit" class="btn btn-sm btn-warning me-2" (click)="handleEdit(row)" title="Editar">
                  <i class="bi bi-pencil"></i>
                </button>
                <button *ngIf="onDelete" class="btn btn-sm btn-danger" (click)="openDeleteModal(row)" title="Eliminar">
                  <i class="bi bi-trash"></i>
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <!-- Modal de confirmación de borrado -->
      <div class="tablecrud-modal-backdrop" *ngIf="showDeleteModal"></div>
      <div class="tablecrud-modal-outer" *ngIf="showDeleteModal">
        <div class="tablecrud-modal-card">
          <div class="tablecrud-modal-header">¿Seguro que deseas eliminar este registro?</div>
          <div>Esta acción no se puede deshacer.</div>
          <div class="tablecrud-modal-footer">
            <button class="btn btn-danger tablecrud-modal-btn" (click)="confirmDelete()">Eliminar</button>
            <button class="btn btn-secondary tablecrud-modal-btn" (click)="closeDeleteModal()">Cancelar</button>
          </div>
  <div *ngIf="deleteError" class="mt-2" style="color: #d32f2f; font-weight: bold;">
    {{ deleteError }}
  </div>

        </div>
      </div>
    </div>
  `
})
export class TableCrudComponent implements OnChanges {
  @Input() columns: { key: string, label: string }[] = [];
  @Input() data: any[] = [];
  @Input() emptyText = '';
  @Input() loading = false;
  @Output() onEdit = new EventEmitter<any>();
  @Input() onDelete: (row: any) => Promise<any> = async () => {};

  showDeleteModal = false;
  rowToDelete: any = null;
  deleteError: string = '';

  constructor(private cdr: ChangeDetectorRef) {}

  ngOnChanges() {
    console.log('TableCrudComponent data:', this.data);
    console.log('TableCrudComponent columns:', this.columns);
  }

  handleEdit(row: any) {
    // Validación personalizada si se provee onValidate
    if ((this as any).onValidate) {
      const error = (this as any).onValidate(row);
      if (error) {
        alert(error);
        return;
      }
    }
    this.onEdit.emit(row);
  }

  openDeleteModal(row: any) {
    this.rowToDelete = row;
    this.deleteError = '';
    this.showDeleteModal = true;
  }

  closeDeleteModal() {
    this.showDeleteModal = false;
    this.rowToDelete = null;
    setTimeout(() => { this.deleteError = ''; }, 200);
  }

  async confirmDelete() {
    if (this.onDelete && this.rowToDelete) {
      this.deleteError = '';
      try {
        await this.onDelete(this.rowToDelete);
        this.closeDeleteModal();
      } catch (err: any) {
        console.error('Error al eliminar (modal):', err);
        if (err && err.error) {
          this.deleteError = err.error;
        } else if (err && err.message) {
          this.deleteError = err.message;
        } else if (typeof err === 'string') {
          this.deleteError = err;
        } else {
          this.deleteError = 'Error al eliminar';
        }
        this.cdr.markForCheck();
        console.log('deleteError asignado:', this.deleteError);
        return;
      }
    }
  }
}
